name: fujitsu

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  fujitsu:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: oss-dashboard
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          -v /tmp/oss-dashboard-${{ GITHUB_ACTION }}:/var/lib/postgresql/data:rw
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/cache@v2
        with:
          path: /tmp/oss-dashboard-${{ GITHUB_ACTION }}
          key: ${{ runner.os }}-postgres
      - run:  docker-compose up dashboard
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
